language: php

php:
  - 5.6

stages:
    - test

test:
    stage: test
    script:
        - ./vendor/bin/phpcs -n -p --extensions=php --standard=PSR2 ./application

pages:
  stage: deploy
  only:
    - master        
        
   
