language: php

php:
  - 5.6
  - hhvm-3.18
  - hhvm-nightly

before_script:
  - curl -sSfL -o ~/.phpenv/versions/hhvm/bin/phpunit https://phar.phpunit.de/phpunit-5.7.phar
  
install:
  - composer install

test:
    stage: test
    script:
        - php vendor/bin/phpcs -n -p --extensions=php --standard=PSR2 ./application
pages:
  stage: deploy
  dependencies:
    - test
  only:
    - master  

       