language: php

php:
  - 5.6

before_install:
  - chmod +x build.sh
  
install:
  - composer install

test:
    stage: test
    script:
        - php vendor/bin/phpcs -n -p --extensions=php --standard=PSR2 ./application
pages:
  stage: deploy
  dependencies:
    - test
  only:
    - master  
    
script: ./build.sh    
       